title:              Blogs
email:              gauravcjoshi17@gmail.com
description:        A blog about my journey through open source
author:             Gaurav Joshi
baseurl:            "" #"/Blogs"
url:                "https://gaurav17joshi.github.io"

# Social Profiles
twitter_username:   
github_username:    gaurav17joshi
facebook_username:  
instagram_username:  
linkedin_username:  

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
